version: "3"

services:
  db:
    container_name: fit_db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./back/tmp/db:/var/lib/postgresql/data

  back:
    container_name: fit_back
    build: back/
    volumes:
      - ./back:/app
    depends_on:
      - db

  front:
    container_name: fit_front
    build: front
    command: npm run dev
    # command: npm run storybook
    volumes:
      - ./front/src:/app
    ports:
      - 8080:3000
    depends_on:
      - back